/*
 *   This file takes the questionSets object array generated by quiz.js and turns it into HTML
 *
 * * * */

function checkAnswers() {

	//initialize score counter
	let score = 0

	//loop through all the answers given and increase score counter when an answer is correct
	for(let i = 0; i < questionSets.length; i++) {

		//find which option the user selected as an answer
		const answer = document.querySelector(`input[name="question${i}"]:checked`)

		//check if the option was valid
		if (!answer) continue

		answer.value == questionSets[i].answer ? ++score : console.log("Answer was incorrect")
	}

	//calculate how many answers were correct and store as a value in localStorage
	localStorage.setItem("score", ((100 * score) / questionSets.length) + "%");

	//send the user to the results page
	window.location.href = "../results-page/result.html";
}



//initialize value for holding the markup for all the questions and options
let outputMarkup = ""

//loop through the questionSets object array generated by quiz.js to convert its properties into markup
for(let outputQuestionIndex = 0; outputQuestionIndex < questionSets.length; outputQuestionIndex++) {

	outputMarkup += `<fieldset><h3>Question ${outputQuestionIndex + 1} of ${questionSets.length}: ${questionSets[outputQuestionIndex].text}</h3><div class="options">`

	//loop through the answer options array
	for(let outputOptionIndex = 0; outputOptionIndex < questionSets[outputQuestionIndex].options.length; outputOptionIndex++) {

		outputMarkup += `<input id="question${outputQuestionIndex}option${outputOptionIndex}" name="question${outputQuestionIndex}" type="radio" value="${outputOptionIndex}" autocomplete="off" required /><label for="question${outputQuestionIndex}option${outputOptionIndex}">${questionSets[outputQuestionIndex].options[outputOptionIndex]}</label>`
	}

	outputMarkup += '</div></fieldset>'
}

//add the "go to results" button for the end of the quiz
outputMarkup += '<button id="finishquiz" onclick="checkAnswers()">Go to Results</button>'

//insert generated markup into the #questionssets element
document.getElementById("questionsets").innerHTML += outputMarkup

//grab the name entered by the user on the registration paage and display it in the #playername element
document.querySelector("#playername").innerHTML = localStorage.getItem("name");
