/*
 *   This file takes the questionSets object array generated by quiz.js and turns it into HTML
 *
 * * * */

function checkAnswers() {

	let score = 0

	for(let i = 0;i < questionSets.length; i++) {
		document.querySelector(`input[name="question${i}"]:checked`).value == questionSets[i].answer ? ++score : console.log("Answer was incorrect")
	}
	localStorage.setItem("score", ((100 * score) / questionSets.length) + "%");
	window.location.href = "../results-page/result.html";
}

let element = document.getElementById("questionsets")
let outputMarkup = ""

for(let outputQuestionIndex = 0; outputQuestionIndex < questionSets.length; outputQuestionIndex++) {

	outputMarkup += `<fieldset><h3>Question ${outputQuestionIndex + 1} of ${questionSets.length}: ${questionSets[outputQuestionIndex].text}</h3><div class="options">`

	for(let outputOptionIndex = 0;outputOptionIndex < questionSets[outputQuestionIndex].options.length; outputOptionIndex++) {

		outputMarkup += `<input id="question${outputQuestionIndex}option${outputOptionIndex}" name="question${outputQuestionIndex}" type="radio" value="${outputOptionIndex}" autocomplete="off" required /><label for="question${outputQuestionIndex}option${outputOptionIndex}">${questionSets[outputQuestionIndex].options[outputOptionIndex]}</label>`
	}

	outputMarkup += '</div></fieldset>'
}

//add the "go to results" button
outputMarkup += '<button id="finishquiz" onclick="checkAnswers()">Go to Results</button>'

element.innerHTML += outputMarkup

document.querySelector("#playername").innerHTML = localStorage.getItem("name");
